version: '3.8'

volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-etc:
    name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log

services:

  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment:
      TZ: "${TZ}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
    volumes:
      - ./mongodata:/data/db
    ports:
      - ${MONGO_EXTERNAL_PORT}:27017

  emqx:
    container_name: emqx
    image: emqx/emqx:4.4.14
    restart: always
    ports:
      - 18083:18083
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 8085:8081

    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log

    links:
      - mongo

    extra_hosts:
      - "localhost:192.168.50.27"

    environment:
      
      EMQX_NAME: Safety_APP
      EMQX_HOST: 127.0.0.1

      TZ: "${TZ}"

      # Contraseña al Dasgboard
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "${EMQX_USER_PASS}"
      # Contraseña API
      EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: "${EMQX_APP_SECRET}"

      # Configuración de Atentificación MongoDB
      EMQX_ALLOW_ANONYMOUS: "false"

      # Conexión con MongoDB
      EMQX_AUTH__MONGO__TYPE: single
      EMQX_AUTH__MONGO__TOPOLOGY__POOL_SIZE: 1
      EMQX_AUTH__MONGO__TOPOLOGY__MAX_OVERFLOW: 0
      
      EMQX_AUTH__MONGO__SERVER: "mongo:${MONGO_EXTERNAL_PORT}"
      EMQX_AUTH__MONGO__POOL: 8
      
      EMQX_AUTH__MONGO__LOGIN: "${MONGO_USER}"
      EMQX_AUTH__MONGO__PASSWORD: "${MONGO_PASS}"
      EMQX_AUTH__MONGO__AUTH_SOURCE: admin

      EMQX_AUTH__MONGO__DATABASE: "safety"
      EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "emqxauthrules"

      EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser"
      EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"
      EMQX_AUTH__MONGO__SUPER_QUERY: "off"

      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
      EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"

      # Activación de la Lista de Control de Acceso (ACL)
      EMQX_AUTH__MONGO__ACL_QUERY: "on"
      EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR: "username=%u"

      # Activación de Plugins principales
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_management,emqx_dashboard,emqx_auth_mongo"

      # Configuración Broker EMQX
      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000